/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AiEmojis {
        "token": string;
    }
    interface WcTextbox {
    }
}
declare global {
    interface HTMLAiEmojisElement extends Components.AiEmojis, HTMLStencilElement {
    }
    var HTMLAiEmojisElement: {
        prototype: HTMLAiEmojisElement;
        new (): HTMLAiEmojisElement;
    };
    interface HTMLWcTextboxElement extends Components.WcTextbox, HTMLStencilElement {
    }
    var HTMLWcTextboxElement: {
        prototype: HTMLWcTextboxElement;
        new (): HTMLWcTextboxElement;
    };
    interface HTMLElementTagNameMap {
        "ai-emojis": HTMLAiEmojisElement;
        "wc-textbox": HTMLWcTextboxElement;
    }
}
declare namespace LocalJSX {
    interface AiEmojis {
        "token"?: string;
    }
    interface WcTextbox {
    }
    interface IntrinsicElements {
        "ai-emojis": AiEmojis;
        "wc-textbox": WcTextbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ai-emojis": LocalJSX.AiEmojis & JSXBase.HTMLAttributes<HTMLAiEmojisElement>;
            "wc-textbox": LocalJSX.WcTextbox & JSXBase.HTMLAttributes<HTMLWcTextboxElement>;
        }
    }
}
